server:
  port: 80
  servlet:
    context-path: /dept-consumer

spring:
  application:
    name: springcloud-consumer-dept

#eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
    fetch-registry: true
    register-with-eureka: true #服务消费方  false 不需要注册本服务
  instance:
    instance-id: springcloud-consumer-dept80 #修改eureka上的默认描述信息

#info eureka info配置
info:
  app.name: wuj-springcloud
  company.name: wuj.com.cn