server:
  port: 8002
  servlet:
    context-path: /dept-provider

#mybatis配置
mybatis:
  type-aliases-package: com.wuj.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:  classpath:mybatis/mapper/*.xml
#spring配置

spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.133.110/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root123

logging:
  level:
    com.wuj.springcloud.dao : debug

#eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,
  instance:
    instance-id: springcloud-provider-dept8002 #修改eureka上的默认描述信息

#info eureka info配置
info:
  app.name: wuj-springcloud
  company.name: wuj.com.cn
